language: python
python:
    - '2.7'
sudo: false
cache:
    directories:
        - "~/.platformio"
install:
    - pip install -U platformio
script:
    - pushd examples/master && pio run && popd
    - pushd examples/moduleInfo && pio run && popd
    - pushd examples/slave && pio run && popd
    - pushd examples/wize2mqtt && cp configuration.sample.h confirguration.h && pio run && popd
