language: python
python:
    - '2.7'
sudo: false
cache:
    directories:
        - "~/.platformio"
install:
    - pip install -U platformio
script:
    - pushd examples/moduleInfo && pio run && popd
    - pushd examples/slave/slave_allwize_k2 && pio run && popd
    - pushd examples/wize2mqtt && cp configuration.sample.h configuration.h && pio run && popd
